"""Tablet keepalive policy selection — no Spot SDK required."""

from __future__ import annotations

import sys
from pathlib import Path
from types import SimpleNamespace

import yaml

REPO = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(REPO / "adapters" / "adapter_ros2"))

from spot_clear_keepalive import load_spot_login, tablet_policy_ids  # noqa: E402


def test_tablet_policy_ids_drops_spotapp_and_keeps_autopolicy():
    statuses = [
        SimpleNamespace(
            policy_id=1,
            policy=SimpleNamespace(name="tablet-stop", user_id="bosdyn.android.spotapp abc"),
        ),
        SimpleNamespace(
            policy_id=2,
            policy=SimpleNamespace(name="estop id '5' (autogenerated)", user_id=""),
        ),
        SimpleNamespace(
            policy_id=3,
            policy=SimpleNamespace(name="", user_id="bosdyn.android.spotapp xyz"),
        ),
        SimpleNamespace(
            policy_id=4,
            policy=SimpleNamespace(name="", user_id=""),
        ),
    ]
    assert tablet_policy_ids(statuses) == [1, 3]


def test_load_spot_login_reads_mist_ros_parameters(tmp_path):
    path = tmp_path / "spot.yaml"
    path.write_text(yaml.safe_dump({
        "/**": {
            "ros__parameters": {
                "hostname": "192.168.50.3",
                "username": "mistlab",
                "password": "secret",
            }
        }
    }))
    assert load_spot_login(path) == ("192.168.50.3", "mistlab", "secret")
