<script lang="ts">
  /**
   * Tactical 3D Map, powered by Three.js.
   *
   * Renders the true 3D map generated by the robots (accumulated voxel terrain with real heights,
   * walls, obstacles, and ceiling) using real map grid and point cloud data from the robots.
   *
   * Features:
   * - Extruded 3D chevron robot symbols in team colors with bevels and headlights
   * - Interactive robot selection (click / shift-click)
   * - Interactive navigation goal targeting on the 3D ground plane
   * - Ceiling cutoff slider to remove roofs and inspect interior rooms
   * - 3D global & local routes, movement trails, sensor arcs, and footprints
   * - 3D holographic waypoint beacons and detection crystals
   * - 3D tactical terrain grid and network heatmaps
   */
  import { onMount, untrack } from 'svelte';
  import * as THREE from 'three';
  import { Box, Check, Compass, Crosshair, Eye, Layers, Sliders, Sparkles, X } from 'lucide-svelte';
  import { fleet } from '$lib/stores/fleet.svelte';
  import { mapStore } from '$lib/stores/mapstore.svelte';
  import { mapRobots } from '$lib/stores/mapRobots.svelte';
  import { replicaTactical } from '$lib/stores/replicaTactical.svelte';
  import { settings } from '$lib/stores/settings.svelte';
  import { navigation } from '$lib/stores/navigation.svelte';
  import { review } from '$lib/stores/review.svelte';
  import { detectionCatalog } from '$lib/stores/detection.svelte';
  import { trails as trailStore } from '$lib/stores/trails.svelte';
  import { actions } from '$lib/api/connection';
  import { robotDisplayName } from '$lib/robotDisplayName';
  import { QUALITY, type Quality, type TerrainData } from './terrainData';
  import {
    replicaSelectionKey,
    type ReplicaTacticalCloud,
    type ReplicaTacticalSelection
  } from './replicaTactical';
  import { ReplicaCloudLoad } from './replicaCloudLoad';
  import {
    liveRobotToMapRobot,
    postLiveReplicaGoal
  } from './liveReplicaFrame';
  import { Map3DScene } from './Map3DScene';
  import { GaussianFetch } from './gaussianFetch';
  import { RenderLoop } from './renderLoop';
  import { SceneInteraction, type InteractionScene, type NDC } from './sceneInteraction';
  import { sceneDrawInputs } from './sceneInputs';
  import { isDeploymentComposite } from '../replicas/replicaCatalogue';
  import type { MapRobot } from '../map/mapRobot';
  import type { Map3DRenderMode, Map3DColorMode } from './types';

  let {
    active = false,
    follow = false,
    showGrid = true,
    showTrails = true,
    showLabels = true,
    showSensors = false,
    showPlans = true,
    showNetwork = false,
    trails = new Map<string, { x: number; y: number }[]>(),
    onCameraInteraction,
    onCursorChange
  }: {
    active?: boolean;
    follow?: boolean;
    showGrid?: boolean;
    showTrails?: boolean;
    showLabels?: boolean;
    showSensors?: boolean;
    showPlans?: boolean;
    showNetwork?: boolean;
    trails?: Map<string, { x: number; y: number }[]>;
    onCameraInteraction?: () => void;
    onCursorChange?: (coords: { x: number; y: number } | null) => void;
  } = $props();

  let canvas = $state<HTMLCanvasElement | null>(null);
  let scene: Map3DScene | null = null;
  const tacticalReplica = $derived(replicaTactical.selection);
  const liveTactical = $derived(
    Boolean(tacticalReplica && replicaTactical.preference === 'auto')
  );
  // The server-composed deployment composite is labelled as such: it places
  // each robot's own component by its surveyed start pose and is not a
  // verified merge.
  const compositeTactical = $derived(
    Boolean(tacticalReplica && isDeploymentComposite(tacticalReplica.componentId))
  );

  // Cloud & Terrain State
  let points = $state(0);
  let voxels = $state(0);
  let robotsOnCloud = $state<string[]>([]);
  let replicaCloud = $state<Pick<ReplicaTacticalCloud, 'view' | 'partial' | 'frameKey'> | null>(null);
  let error = $state<string | null>(null);

  // Render & Color Modes
  let renderMode = $state<Map3DRenderMode>('voxels');
  let quality = $state<Quality>('balanced');
  let hasRgb = $state(false);
  let gaussianCount = $state(0);
  let gaussianStatus = $state('No reconstruction loaded');
  let gaussianBuffer: ArrayBuffer | null = null;
  let colorMode = $state<Map3DColorMode>('elevation');
  let pointSize = $state<number>(0.07);

  // Ceiling Slider State
  let ceilingMax = $state(2.6);
  let ceilingMin = $state(0.0);
  let ceilingCutoff = $state(2.3); // Initial cutoff: open interior view

  // Interaction State: the gestures themselves live in sceneInteraction.ts.
  let dragging = $state(false);
  let cursor3D = $state<{ x: number; y: number; z: number } | null>(null);
  let detectionScreenPos = $state<{ sx: number; sy: number } | null>(null);
  // Membership and live telemetry belong to the map, not this dimension.
  $effect(() => {
    const selection = tacticalReplica;
    mapRobots.setCloud(active, selection ? replicaSelectionKey(selection) : '',
      replicaCloud?.view.solution_order_known === true && replicaCloud.view.selected &&
      replicaCloud.view.session_id === selection?.sessionId &&
      replicaCloud.view.component_id === selection?.componentId
        ? { frameId: replicaCloud.view.selected.frame_id, solutionOrder: replicaCloud.view.solution_order }
        : null);
  });

  function robotsOnMap(): MapRobot[] {
    const ids = mapRobots.ids;
    if (tacticalReplica) {
      const liveReplica = mapRobots.live;
      if (!liveReplica) return [];
      const age = (performance.now() - liveReplica.receivedAt) / 1000;
      return liveReplica.frame.robots.filter((robot) => ids.includes(robot.robot_id))
        .map((robot) => liveRobotToMapRobot(robot, fleet.get(robot.robot_id) ?? undefined, age));
    }
    return fleet.robots.filter((robot) => ids.includes(robot.robot_id));
  }

  // Public camera control methods for ViewControls toolbar
  export function centreFleet() {
    if (!scene) return;
    scene.centreRobots(robotsOnMap());
    requestRender();
  }

  export function centreSelected() {
    if (!scene) return;
    scene.centreRobots(robotsOnMap(), new Set(fleet.selected));
    requestRender();
  }

  export function zoomBy(factor: number) {
    if (!scene) return;
    scene.zoomBy(factor);
    requestRender();
  }

  export function rotateBy(angleDelta: number) {
    if (!scene) return;
    scene.rotateBy(angleDelta);
    requestRender();
  }

  export function resetRotation() {
    if (!scene) return;
    scene.resetRotation();
    requestRender();
  }

  export function fitCloud() {
    if (!scene) return;
    scene.fitMap();
    requestRender();
  }

  export function setCeiling(height: number) {
    ceilingCutoff = height;
    if (scene) {
      scene.setCeiling(height);
      requestRender();
    }
  }

  export function setIsometricView() {
    if (!scene) return;
    scene.yaw = -0.785; // 45 deg
    scene.pitch = 0.96; // 55 deg
    requestRender();
  }

  export function cutCeilingQuick() {
    setCeiling(Math.max(ceilingMin, Math.min(ceilingMin + 2.1, ceilingMax - 0.4)));
  }

  export function resetCeiling() {
    setCeiling(ceilingMax + 0.2);
  }

  export function setRenderMode(mode: Map3DRenderMode) {
    renderMode = mode;
    if (scene) {
      scene.terrain.setRenderMode(mode);
      scene.gaussians.group.visible = mode === 'gaussians';
      scene.terrain.setGaussianProxy(mode === 'gaussians' && gaussianCount === 0);
      if (mode === 'gaussians') {
        gaussianStatus = gaussianCount
          ? `${gaussianCount.toLocaleString()} Gaussian splats`
          : 'Point-cloud proxy · checking for Gaussian reconstruction';
        void fetchGaussians();
      }
      requestRender();
    }
  }

  export function setColorMode(mode: Map3DColorMode) {
    colorMode = mode;
    if (scene) {
      scene.terrain.setColorMode(mode);
      requestRender();
    }
  }

  export function setPointSize(size: number) {
    pointSize = size;
    if (scene) {
      scene.terrain.setPointSize(size);
      requestRender();
    }
  }

  let worker: Worker | null = null;
  let lastScope: string | null = null;
  let mounted = $state(false);
  // The replica point cloud, loaded by replicaCloudLoad.ts. A selection or
  // frame change rebuilds at once through the direct fetchCloud() calls;
  // geometry-only revisions are picked up on its slower cadence.
  const cloudLoad = new ReplicaCloudLoad(
    { selection: () => tacticalReplica, hasScene: () => scene !== null },
    prepareCloud
  );
  let renderedOwnerIds: string[] = [];
  const seenMapEpochs = new Map<string, string>();
  $effect(() => {
    const epochs = mapStore.robotMapEpochs;
    for (const [robotId, epoch] of Object.entries(epochs)) {
      if (seenMapEpochs.get(robotId) === epoch) continue;
      seenMapEpochs.set(robotId, epoch);
      const owner = renderedOwnerIds.indexOf(robotId);
      cloudLoad.cancel();
      if (owner >= 0) {
        scene?.terrain.removeOwner(owner, quality);
        scene?.gaussians.clear();
      }
      points = scene?.terrain.pointCount ?? 0;
      voxels = scene?.terrain.voxelCount ?? 0;
      robotsOnCloud = robotsOnCloud.filter(id => id !== robotId);
      cloudLoad.forgetRevision(true);
      gaussianFetch.forget();
      scene?.layers.invalidate();
      requestRender();
      void fetchCloud();
    }
  });
  let firstCloud = true;

  function gaussianScope() {
    if (!tacticalReplica) return '';
    return `?session_id=${encodeURIComponent(tacticalReplica.sessionId)}`
      + `&component_id=${encodeURIComponent(tacticalReplica.componentId)}`;
  }

  function sourceScope() {
    if (!tacticalReplica && replicaTactical.autoStatus === 'waiting-global') {
      return 'blocked:global-waiting-for-component';
    }
    return tacticalReplica ? `replica:${replicaSelectionKey(tacticalReplica)}` : 'replica:none';
  }

  const waitingForGlobalComponent = $derived(
    !tacticalReplica &&
    replicaTactical.preference === 'auto' &&
    replicaTactical.autoStatus === 'waiting-global' &&
    mapStore.viewMode === 'global'
  );

  function replicaPublicationLabel(view: ReplicaTacticalCloud['view']) {
    if (isDeploymentComposite(view.component_id)) return 'deployment composite';
    return view.scope === 'fleet' ? 'fleet snapshot' : `replica r${view.revision}`;
  }

  function replicaPublicationTitle(view: ReplicaTacticalCloud['view']) {
    if (isDeploymentComposite(view.component_id) && view.snapshot_id) {
      return `Composite of ${view.sources?.length ?? 0} robot components placed by surveyed start poses; not a verified merge (${view.snapshot_id.slice(0, 12)})`;
    }
    return view.scope === 'fleet' && view.snapshot_id
      ? `Aggregate snapshot ${view.snapshot_id.slice(0, 12)}`
      : undefined;
  }

  function prepareCloud(
    id: number,
    signal: AbortSignal,
    positions: Float32Array,
    owners: Uint8Array,
    rgb?: Uint8Array
  ) {
    return new Promise<TerrainData>((resolve, reject) => {
      worker!.onmessage = (
        e: MessageEvent<{ id: number; data: TerrainData; error?: string }>
      ) => {
        if (e.data.id === id)
          e.data.error ? reject(new Error(e.data.error)) : resolve(e.data.data);
      };
      worker!.onerror = () => reject(new Error('Map preparation failed'));
      signal.addEventListener(
        'abort',
        () => reject(new DOMException('Aborted', 'AbortError')),
        { once: true }
      );
      worker!.postMessage({ id, positions, owners, rgb, quality }, [
        positions.buffer,
        owners.buffer,
        ...(rgb ? [rgb.buffer] : [])
      ]);
    });
  }

  function displayTerrain(data: TerrainData, names: string[], rgbPresent: boolean, resetView: boolean) {
    if (!scene) return;
    renderedOwnerIds = names;
    hasRgb = rgbPresent;
    if (!hasRgb && colorMode === 'camera') setColorMode('elevation');
    const bounds = scene.terrain.build(data, names.map((id) => fleet.colorOf(id)));
    scene.layers.invalidate();
    points = scene.terrain.pointCount;
    voxels = scene.terrain.voxelCount;
    robotsOnCloud = names;
    ceilingMin = bounds.minZ;
    ceilingMax = Math.max(bounds.maxZ, bounds.minZ + 0.1);
    if (resetView && points) {
      // The opening cut hides the ceiling of a single-storey interior. It is
      // measured from the floor the points stand on (their 10th z-percentile),
      // not the lowest point: a descending tunnel or a drifting robot's frame
      // puts the minimum metres below the floor, and a cut 2.3 m above that
      // left only the deepest fragment visible. A map spanning more than one
      // storey has no single plane to open it with, so it starts uncut.
      const zs = Array.from({ length: points }, (_, i) => data.xyz[i * 3 + 2]).sort((a, b) => a - b);
      const floor = zs[Math.floor(zs.length * 0.1)];
      ceilingCutoff = ceilingMax - floor > 4.0 ? ceilingMax + 0.2 : Math.min(ceilingMax + 0.2, floor + 2.3);
      scene.setCeiling(ceilingCutoff);
      scene.fitMap();
      firstCloud = false;
    }
    requestRender();
  }

  async function fetchCloud() {
    if (!scene || !worker || !active || document.hidden || cloudLoad.busy || !tacticalReplica) return;
    if (waitingForGlobalComponent) return;
    const result = await cloudLoad.load();
    if (!result) return;
    if (result.kind === 'current') {
      error = null;
      return;
    }
    if (result.kind === 'failed') {
      error = result.message;
      return;
    }
    const { data, cloud, resetView } = result;
    try {
      displayTerrain(data, cloud.ownerIds, Boolean(cloud.rgb), resetView);
      cloudLoad.commit(cloud);
      replicaCloud = { view: cloud.view, partial: cloud.partial, frameKey: cloud.frameKey };
      error = null;
    } catch (cause) {
      error = cause instanceof Error ? cause.message : String(cause);
    }
  }

  const gaussianFetch = new GaussianFetch({ scope: gaussianScope, hasScene: () => scene !== null });

  function showGaussianFailure(message: string) {
    const cached = gaussianCount > 0;
    scene?.terrain.setGaussianProxy(renderMode === 'gaussians' && !cached);
    requestRender();
    gaussianStatus = `${cached ? `${gaussianCount.toLocaleString()} cached Gaussian splats` : 'Point-cloud proxy'} · ${message}`;
  }

  async function fetchGaussians() {
    if (!scene || !active || document.hidden || gaussianFetch.busy) return;
    const result = await gaussianFetch.fetch();
    if (!result || result.kind === 'unchanged') return;
    if (result.kind === 'failed') {
      showGaussianFailure(result.message);
      return;
    }
    if (!scene) return;
    if (result.kind === 'missing') {
      scene.gaussians.clear();
      gaussianCount = 0;
      gaussianBuffer = null;
      scene.terrain.setGaussianProxy(renderMode === 'gaussians');
      gaussianStatus = 'Point-cloud proxy · no Gaussian reconstruction available';
      requestRender();
      return;
    }
    try {
      const firstModel = scene.gaussians.count === 0;
      scene.gaussians.load(result.buffer, QUALITY[quality].splats);
      scene.terrain.setGaussianProxy(false);
      if (!points && firstModel && scene.gaussians.count) {
        ceilingMin = scene.gaussians.bounds.min.z;
        ceilingMax = Math.max(ceilingMin + 0.1, scene.gaussians.bounds.max.z);
        ceilingCutoff = ceilingMax + 0.2;
        scene.setCeiling(ceilingCutoff);
        scene.fitMap();
      }
      gaussianBuffer = result.buffer;
      gaussianFetch.accept(result.etag);
      gaussianCount = scene.gaussians.count;
      gaussianStatus = `${gaussianCount.toLocaleString()} Gaussian splats`;
      requestRender();
    } catch (e) {
      showGaussianFailure(e instanceof Error ? e.message : String(e));
    }
  }

  function setQuality(value: Quality) {
    quality = value;
    if (scene) {
      scene.quality = value;
      scene.resize();
      if (gaussianBuffer) {
        scene.gaussians.load(gaussianBuffer, QUALITY[value].splats);
        gaussianCount = scene.gaussians.count;
        gaussianStatus = `${gaussianCount.toLocaleString()} Gaussian splats`;
      }
    }
    cloudLoad.abort();
    if (tacticalReplica) cloudLoad.requireRebuild();
    void fetchCloud();
  }

  $effect(() => {
    const currentScope = sourceScope();
    if (!mounted || !active) return;
    if (currentScope === lastScope) return;
    lastScope = currentScope;
    cloudLoad.cancel();
    cloudLoad.forgetRevision(false);
    replicaCloud = null;
    gaussianFetch.abort();
    gaussianFetch.forget();
    gaussianBuffer = null;
    scene?.terrain.clear();
    scene?.gaussians.clear();
    points = 0;
    voxels = 0;
    gaussianCount = 0;
    void fetchCloud();
    if (renderMode === 'gaussians') void fetchGaussians();
  });

  // Pointer & RTS Mouse Interaction
  function getNDC(e: PointerEvent): NDC {
    if (!canvas) return { x: 0, y: 0 };
    const rect = canvas.getBoundingClientRect();
    const x = ((e.clientX - rect.left) / rect.width) * 2 - 1;
    const y = -(((e.clientY - rect.top) / rect.height) * 2 - 1);
    return { x, y };
  }

  const ndcVector = (ndc: NDC) => new THREE.Vector2(ndc.x, ndc.y);

  /** Map3DScene as pointer handling sees it. */
  function interactionScene(): InteractionScene | null {
    const current = scene;
    if (!current) return null;
    return {
      get yaw() { return current.yaw; },
      set yaw(value) { current.yaw = value; },
      get pitch() { return current.pitch; },
      set pitch(value) { current.pitch = value; },
      panBy: (dx, dy) => current.panBy(dx, dy),
      groundAt: (ndc) => current.raycastGround(ndcVector(ndc)),
      robotAt: (ndc) => current.raycastRobot(ndcVector(ndc)),
      detectionAt: (ndc) => current.layers.raycastDetection(ndcVector(ndc), current.camera),
      reticle: current.layers.cursorReticle
    };
  }

  const interaction = new SceneInteraction<ReplicaTacticalSelection>({
    scene: interactionScene,
    requestRender: () => requestRender(),
    cameraMoved: () => onCameraInteraction?.(),
    setDragging: (value) => (dragging = value),
    setCursor: (point, planar) => {
      cursor3D = point ? { x: point.x, y: point.y, z: point.z } : null;
      onCursorChange?.(planar);
    },
    goalMode: () => navigation.goalMode,
    replicaShown: () => Boolean(tacticalReplica),
    liveReplica: () =>
      tacticalReplica && liveTactical
        ? {
            selection: tacticalReplica,
            solutionOrder: replicaCloud?.view.solution_order,
            solutionOrderKnown: replicaCloud?.view.solution_order_known === true
          }
        : null,
    drawnRobotIds: () => robotsOnMap().map((robot) => robot.robot_id),
    selected: () => fleet.selected,
    canNavigate: (id) => fleet.can(id, 'navigate'),
    sendGoal: (live, id, goal) =>
      postLiveReplicaGoal(live.selection, id, live.solutionOrder ?? null, goal, undefined, navigation.exploreIfUnknown),
    goalFailed: (message) => (error = message),
    cancelGoalMode: () => navigation.cancelGoalMode(),
    finishGoal: (goal) => navigation.finishGoal(goal),
    selectRobot: (id, additive) => {
      fleet.select(id, additive);
      actions.selectRobots(fleet.selected);
    },
    selectDetection: (id) => review.select(id),
    detectionSelected: () => review.selected
  });

  function onPointerDown(e: PointerEvent) {
    if (!canvas) return;
    canvas.setPointerCapture(e.pointerId);
    interaction.pointerDown({ x: e.clientX, y: e.clientY }, e.button, e.shiftKey);
  }

  function onPointerMove(e: PointerEvent) {
    if (!scene || !canvas) return;
    interaction.pointerMove({ x: e.clientX, y: e.clientY }, getNDC(e));
  }

  function onPointerUp(e: PointerEvent) {
    if (!canvas || !scene) return;
    try {
      canvas.releasePointerCapture(e.pointerId);
    } catch {}
    void interaction.pointerUp(e.button, e.type === 'pointercancel', () => getNDC(e), e.shiftKey);
  }

  function onWheel(e: WheelEvent) {
    e.preventDefault();
    if (!scene) return;
    onCameraInteraction?.();
    scene.zoomBy(e.deltaY < 0 ? 1.15 : 1 / 1.15);
    requestRender();
  }

  function onContextMenu(e: MouseEvent) {
    e.preventDefault(); // Prevent browser right-click menu
  }

  // Animation & Rendering Loop: render on demand, see renderLoop.ts.
  const renderLoop = new RenderLoop({
    canStart: () => mounted && active && !document.hidden,
    frameInputs: () =>
      scene && active
        ? {
            hidden: document.hidden,
            // A robot held through a gap in its source frame needs frames to keep
            // coming, or its grace period never expires and it is drawn for ever.
            decorating: scene.robotManager.animating || scene.robotManager.retaining,
            fps: QUALITY[quality].fps
          }
        : null,
    draw: drawFrame
  });

  /** Draw on the next animation frame, starting the loop if it had stopped. */
  function requestRender(moving = false) {
    renderLoop.request(moving);
  }

  function drawFrame(timestamp: number, updateLayers: boolean) {
    if (!scene) return;
    const time = timestamp * 0.001;

    // Center on the currently displayed robots. Live component telemetry is
    // already in the selected component frame, so it is safe to follow it.
    if (follow && (!tacticalReplica || liveTactical)) {
      const followRobots = robotsOnMap();
      if (followRobots.length > 0) scene.centreRobots(followRobots);
    }

    const robots = robotsOnMap();
    const getGroundZ = (x: number, y: number) => (scene ? scene.terrain.getGroundZ(x, y) : 0.0);

    scene.robotManager.update(robots, {
      showSensors,
      showLabels,
      time,
      getGroundZ,
      sourceIdentity: tacticalReplica
        ? `${tacticalReplica.scope}\u0000${tacticalReplica.scope === 'robot' ? tacticalReplica.robotId : ''}\u0000${tacticalReplica.sessionId}\u0000${tacticalReplica.componentId}\u0000${replicaCloud?.frameKey ?? ''}`
        : `live\u0000${mapStore.viewMode}\u0000${mapStore.viewRobot ?? 'world'}`,
      markerScale: (position, selected) => {
        const metresPerPixel = 2 * scene!.camera.position.distanceTo(position)
          * Math.tan(THREE.MathUtils.degToRad(scene!.camera.fov) / 2)
          / Math.max(1, scene!.canvas.clientHeight);
        return Math.max(1, Math.min(12, metresPerPixel * (selected ? 26 : 18)));
      }
    });

    if (updateLayers) {
      scene.layers.update({
        robots,
        trails,
        showGrid,
        showTrails: showTrails && !tacticalReplica,
        showPlans: showPlans && (!tacticalReplica || liveTactical),
        showSensors: showSensors && (!tacticalReplica || liveTactical),
        showNetwork: showNetwork && !tacticalReplica,
        time,
        getGroundZ
      });
    }
    // Update active detection screen projection for popover
    const activeDetId = tacticalReplica ? null : review.selected ?? review.focused;
    if (activeDetId) {
      const activeObj = review.proposalOf(activeDetId) ?? review.entityOf(activeDetId);
      if (activeObj) {
        const gz = getGroundZ(activeObj.position.x, activeObj.position.y);
        const v = new THREE.Vector3(activeObj.position.x, activeObj.position.y, gz + 0.4);
        const screenProj = scene.worldToScreen(v);
        detectionScreenPos = screenProj.visible ? { sx: screenProj.sx, sy: screenProj.sy } : null;
      } else {
        detectionScreenPos = null;
      }
    } else {
      detectionScreenPos = null;
    }

    scene.render();
  }

  function pauseScene() {
    // Whatever changed while the map was away is drawn once on return.
    renderLoop.pause();
    cloudLoad.cancel();
    gaussianFetch.abort();
  }

  function resumeScene() {
    if (!scene || !active || document.hidden) return;
    scene.resize();
    requestRender();
    void fetchCloud();
    if (renderMode === 'gaussians') void fetchGaussians();
  }

  // Everything the drawn frame is built from, listed and explained in
  // sceneInputs.ts. Reading it here is what turns a store or prop change into
  // exactly one redraw, instead of the scene being redrawn continuously in
  // case one of them had changed.
  $effect(() => {
    void sceneDrawInputs(
      { fleet, settings, trails: trailStore, mapStore, review, replicaTactical },
      {
        liveReplicaRevision: mapRobots.revision,
        replicaCloud,
        follow,
        showGrid,
        showTrails,
        showLabels,
        showSensors,
        showPlans,
        showNetwork,
        quality,
        renderMode,
        colorMode,
        pointSize
      }
    );
    void mapRobots.ids;
    if (mounted && active) untrack(() => requestRender(true));
  });

  $effect(() => {
    void mapRobots.freshnessRevision;
    if (mounted && active) untrack(() => {
      renderLoop.invalidateFreshness();
      requestRender();
    });
  });

  $effect(() => {
    if (!mounted) return;
    if (!active) {
      untrack(pauseScene);
      return;
    }
    // Wait for the parent's hidden class to clear before measuring the canvas.
    const frame = requestAnimationFrame(resumeScene);
    return () => cancelAnimationFrame(frame);
  });

  $effect(() => {
    // Subscribe before checking the non-reactive scene, which is created on mount.
    const cutoff = ceilingCutoff;
    if (mounted && scene) {
      scene.setCeiling(cutoff);
      untrack(() => requestRender());
    }
  });

  onMount(() => {
    if (!canvas) return;

    try {
      scene = new Map3DScene(canvas);
      scene.terrain.setRenderMode(renderMode);
      scene.terrain.setColorMode(colorMode);
      scene.terrain.setPointSize(pointSize);
      scene.resize();
    } catch (err) {
      error = err instanceof Error ? err.message : String(err);
      return;
    }

    worker = new Worker(new URL('./terrain.worker.ts', import.meta.url), { type: 'module' });
    scene.gaussians.group.visible = renderMode === 'gaussians';
    scene.gaussians.onDirty = () => requestRender();
    mounted = true;
    const splatPoll = window.setInterval(
      () => renderMode === 'gaussians' && void fetchGaussians(),
      5000
    );
    const poll = window.setInterval(() => {
      if (!active) return;
      if (cloudLoad.due()) {
        void fetchCloud();
      }
    }, 1000);

    const ro = new ResizeObserver(() => {
      if (!active || document.hidden) return;
      scene?.resize();
      requestRender();
    });
    ro.observe(canvas);

    const onVisibility = () => document.hidden ? pauseScene() : resumeScene();
    document.addEventListener('visibilitychange', onVisibility);

    return () => {
      mounted = false;
      cloudLoad.cancel();
      mapRobots.setCloud(false, '', null);
      gaussianFetch.abort();
      worker?.terminate();
      worker = null;
      window.clearInterval(splatPoll);
      window.clearInterval(poll);
      renderLoop.stop();
      document.removeEventListener('visibilitychange', onVisibility);
      ro.disconnect();
      scene?.dispose();
      scene = null;
    };
  });
</script>

<div class="relative h-full w-full select-none overflow-hidden bg-[#1e242d]">
  <canvas
    bind:this={canvas}
    class="h-full w-full touch-none {navigation.goalMode && tacticalReplica
      ? 'cursor-crosshair'
      : dragging
        ? 'cursor-grabbing'
        : 'cursor-grab'}"
    onpointerdown={onPointerDown}
    onpointermove={onPointerMove}
    onpointerup={onPointerUp}
    onpointercancel={onPointerUp}
    onwheel={onWheel}
    oncontextmenu={onContextMenu}
  ></canvas>

  <!-- 3D Tactical Status HUD (Top Left) -->
  <div
    class="panel-glow pointer-events-none absolute left-3 bottom-12 z-20 flex max-w-[calc(100%_-_1.5rem)] flex-col gap-1 rounded-[--radius-control]
           border border-border/80 bg-surface/92 px-3 py-2 text-[10px] text-fg-dim shadow-xl"
  >
    <div class="flex items-center gap-2">
      <span
        class="inline-flex h-2 w-2 rounded-full {error && points === 0
          ? 'bg-warn'
          : 'bg-ok'} animate-pulse"
      ></span>
      <span class="font-semibold uppercase tracking-wider text-fg"> 3D Tactical Map </span>
    </div>
    {#if waitingForGlobalComponent}
      <span class="text-warn">Global map is waiting for inter-robot alignment. Select Local to view a robot map.</span>
    {:else if error}
      <span class="text-warn">{error}</span>
      {#if replicaCloud}
        <span title={replicaPublicationTitle(replicaCloud.view)}>
          Keeping {replicaPublicationLabel(replicaCloud.view)} in {replicaCloud.view.selected?.frame_id}
        </span>
      {/if}
    {:else}
      <div class="flex items-center gap-2 font-mono text-fg-muted">
        <span>{points.toLocaleString()} points</span>
        <span class="text-border">·</span>
        <span>{voxels.toLocaleString()} voxels</span>
        <span class="text-border">·</span>
        <span>{robotsOnCloud.length} {tacticalReplica ? 'source' : 'robot'}{robotsOnCloud.length === 1 ? '' : 's'}</span>
        {#if cursor3D}
          <span class="text-border">·</span>
          <span class="text-accent font-medium"
            >({cursor3D.x.toFixed(1)}, {cursor3D.y.toFixed(1)}, {cursor3D.z.toFixed(1)}) m</span
          >
        {/if}
      </div>
      <div class="text-[9px] text-fg-dim/80">
        {#if replicaCloud}
          <span title={replicaPublicationTitle(replicaCloud.view)}>
            {replicaCloud.view.selected?.frame_id} · {replicaPublicationLabel(replicaCloud.view)}
          </span>
          {replicaCloud.partial ? ' · bounded chunk sample' : ''}<br />
        {/if}
        Left-drag to orbit · Right-drag to pan · Scroll to zoom
      </div>
    {/if}
  </div>

  <!-- 3D Controls Bar (Top Right) -->
  <div class="absolute left-3 right-3 top-3 z-20 flex flex-wrap items-center justify-end gap-2">
    {#if tacticalReplica}
      <div class="panel-glow mr-auto flex min-w-0 items-center gap-2 rounded-[--radius-control] border border-accent/30 bg-surface/95 px-3 py-1.5 text-[10px] shadow-2xl">
        <div class="min-w-0">
          <div class="font-semibold text-accent">
            {#if liveTactical && replicaCloud?.view.solution_order_known}
              {#if compositeTactical}
                Live fleet composite (deployment frame)
              {:else}
                Live {tacticalReplica.scope === 'fleet' ? 'fleet' : 'onboard'} map
              {/if}
            {:else if compositeTactical}
              Fleet composite (deployment frame) · read-only
            {:else}
              {tacticalReplica.scope === 'fleet' ? 'Fleet component' : 'Onboard component'} · read-only
            {/if}
          </div>
          <div class="max-w-72 truncate font-mono text-fg-dim" title={tacticalReplica.componentId}>{tacticalReplica.componentId}</div>
        </div>
        {#if !liveTactical}
          <button
            class="rounded bg-surface-2 px-2 py-1 font-semibold text-fg hover:bg-surface-3"
            onclick={() => replicaTactical.useAutomatic()}
          >Live map</button>
        {/if}
      </div>
    {/if}
    <!-- Rendering budgets default to integrated graphics. -->
    <div
      class="panel-glow flex items-center gap-1 rounded-[--radius-control] border border-border/90
             bg-surface/95 p-1 shadow-2xl text-[10px]"
    >
      <span class="px-1 text-[9px] font-semibold uppercase tracking-wider text-fg-dim">View</span>
      {#each [{ id: 'voxels', label: 'Voxels' }, { id: 'mesh', label: 'Mesh' }, { id: 'points', label: 'Points' }, { id: 'gaussians', label: 'Gaussians' }] as mode}
        <button
          class="rounded px-2 py-0.5 {renderMode === mode.id
            ? 'bg-accent text-accent-fg'
            : 'text-fg-muted'} disabled:cursor-not-allowed disabled:opacity-40"
          aria-pressed={renderMode === mode.id}
          onclick={() => setRenderMode(mode.id as Map3DRenderMode)}>{mode.label}</button
        >
      {/each}
      <select
        aria-label="Graphics quality"
        class="rounded bg-surface px-1 py-0.5 text-fg"
        value={quality}
        onchange={(e) => setQuality(e.currentTarget.value as Quality)}
      >
        <option value="low">Low power</option><option value="balanced">Balanced</option><option
          value="high">High detail</option
        >
      </select>
    </div>

    {#if renderMode !== 'gaussians'}
      <div
        class="panel-glow flex items-center gap-1 rounded-[--radius-control] border border-border/90
             bg-surface/95 p-1 shadow-2xl text-[10px]"
      >
        <span class="px-1 text-[9px] font-semibold uppercase tracking-wider text-fg-dim">Color</span
        >
        <button
          class="rounded px-2 py-0.5 font-medium transition-colors {colorMode === 'elevation'
            ? 'bg-accent text-accent-fg shadow-sm'
            : 'text-fg-muted hover:text-fg'}"
          title="Color by elevation (topography / caves / slope height)"
          onclick={() => setColorMode('elevation')}
        >
          Elevation
        </button>
        <button
          class="rounded px-2 py-0.5 font-medium transition-colors {colorMode === 'robot'
            ? 'bg-accent text-accent-fg shadow-sm'
            : 'text-fg-muted hover:text-fg'}"
          title="Color by robot / team source"
          onclick={() => setColorMode('robot')}
        >
          Team
        </button>
        <button
          class="rounded px-2 py-0.5 disabled:opacity-40 {colorMode === 'camera' ? 'bg-accent text-accent-fg' : 'text-fg-muted'}"
          disabled={!hasRgb}
          title={hasRgb ? 'Calibrated camera colors' : 'No calibrated RGB is available for this map yet. New color keyframes require matching camera images, depth and capture-time poses.'}
          aria-pressed={colorMode === 'camera'}
          onclick={() => setColorMode('camera')}>Camera</button
        >
      </div>
    {/if}
    {#if renderMode === 'gaussians'}
      <span role="status" class="rounded bg-surface px-2 py-1 text-xs text-fg-muted"
        >{gaussianStatus}</span
      >
    {/if}
    <!-- Ceiling Cutoff Slider -->
    <div
      class="panel-glow flex items-center gap-2 rounded-[--radius-control] border border-border/90
             bg-surface/95 px-3 py-1.5 shadow-2xl"
    >
      <div
        class="flex items-center gap-1 text-[10px] font-semibold uppercase tracking-wider text-accent"
      >
        <Sliders class="h-3 w-3" />
        <span>Ceiling</span>
      </div>

      <!-- Keep the range step origin fixed as incoming map bounds change. -->
      <input
        type="range"
        min={Math.floor(Math.min(ceilingMin, ceilingCutoff) * 20) / 20}
        max={Math.ceil(Math.max(ceilingMax + 0.2, ceilingCutoff) * 20) / 20}
        step="0.05"
        aria-label="Ceiling cutoff in metres"
        bind:value={ceilingCutoff}
        class="h-1.5 w-24 cursor-pointer appearance-none rounded-full bg-surface-2 accent-accent"
        title="Slide to remove ceiling / roof and view interior"
      />

      <span class="min-w-9 font-mono text-[10px] font-semibold text-fg">
        {ceilingCutoff.toFixed(2)}m
      </span>

      <button
        class="rounded-[--radius-control] bg-surface-2 px-1.5 py-0.5 text-[9px] font-medium text-fg-muted
               transition-colors hover:bg-accent-container hover:text-accent-container-fg"
        title="Slice off the roof to view room/cave interior"
        onclick={cutCeilingQuick}
      >
        Cut
      </button>

      <button
        class="rounded-[--radius-control] bg-surface-2 px-1.5 py-0.5 text-[9px] font-medium text-fg-muted
               transition-colors hover:bg-surface hover:text-fg"
        title="Restore full height ceiling"
        onclick={resetCeiling}
      >
        Full
      </button>

      <button
        class="rounded-[--radius-control] bg-surface-2 px-1.5 py-0.5 text-[9px] font-medium text-accent
               transition-colors hover:bg-accent-container hover:text-accent-container-fg"
        title="Set classic 45° Isometric perspective"
        onclick={setIsometricView}
      >
        <Compass class="h-3 w-3" />
      </button>
    </div>
  </div>

  <!-- Goal Navigation Mode Banner -->
  {#if navigation.goalMode && tacticalReplica}
    {@const canGoal = fleet.selected.filter((id) => fleet.can(id, 'navigate')).length}
    <div
      class="pointer-events-none absolute left-1/2 top-3 -translate-x-1/2 rounded-[--radius-control] border
             border-accent/40 bg-surface/95 px-4 py-2 text-[11px] font-medium text-accent
             shadow-2xl"
    >
      <Crosshair class="mr-1.5 inline h-3.5 w-3.5 animate-spin" />
      Click 3D ground destination for {canGoal} robot{canGoal > 1 ? 's' : ''} · Esc to cancel
    </div>
  {/if}

  <!-- Active Reviewed Object Detection Preview Card in 3D -->
  {#if !tacticalReplica && (review.selected || review.focused) && detectionScreenPos}
    {@const activeDetectionId = review.selected ?? review.focused}
    {@const activeObj = activeDetectionId
      ? (review.proposalOf(activeDetectionId) ?? review.entityOf(activeDetectionId))
      : null}
    {#if activeObj && activeObj.image}
      <div
        class="pointer-events-none absolute z-25 flex -translate-x-1/2 -translate-y-full flex-col items-center pb-3.5"
        style="left: {detectionScreenPos.sx}px; top: {detectionScreenPos.sy}px;"
      >
        <div
          class="flex flex-col items-center overflow-hidden rounded-xl border border-border/80
                 bg-surface/95 p-2 shadow-2xl"
        >
          <img
            src={activeObj.image}
            alt="{detectionCatalog.labelOf(activeObj.class)} detection crop"
            class="h-32 w-32 rounded-lg object-cover shadow-sm"
          />
          <div
            class="mt-1 flex w-full items-center justify-between px-1 text-[10px] font-semibold text-fg"
          >
            <span>{detectionCatalog.labelOf(activeObj.class)}</span>
            <span class="font-normal text-fg-dim">
              {`${Math.round(activeObj.best_score * 100)}%`}
            </span>
          </div>
        </div>
        <div
          class="-mt-1 h-2 w-2 rotate-45 border-b border-r border-border/80 bg-surface shadow-sm"
        ></div>
      </div>
    {/if}
  {/if}
</div>
