<?xml version="1.0"?>
<package format="3">
  <name>swarmdeck_description</name>
  <version>0.1.0</version>
  <description>SwarmDeck robot model</description>
  <maintainer email="swarmdeck@mistlab.ca">SwarmDeck</maintainer>
  <license>MIT</license>
  <buildtool_depend>ament_cmake</buildtool_depend>

  <export><build_type>ament_cmake</build_type></export>
</package>
